return {
    Fire = { Enum.UserInputType.MouseButton1 },
    Reload = { Enum.KeyCode.R },
    Sprint = { Enum.KeyCode.LeftShift, Enum.KeyCode.RightShift },
    Crouch = { Enum.KeyCode.LeftControl, Enum.KeyCode.RightControl },
    Aim = { Enum.KeyCode.Q, Enum.UserInputType.MouseButton2 },
    Interact = { Enum.KeyCode.E },
    Equip = { Enum.KeyCode.One, Enum.KeyCode.Two, Enum.KeyCode.Three, Enum.KeyCode.Four, Enum.KeyCode.Five, Enum.KeyCode.Six }
}